version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: bg-removal-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      # Mount .env file for configuration
      - ./.env:/app/.env:ro
      # Optional: Mount logs directory
      - ./logs:/app/logs
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    # Optional: Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
